### ISSUE TITLE
Question: contao-bootstrap/form + checkedEmail

### ISSUE THREAD

**Issue by reluem** [contao-bootstrap/form#21]
Hi, 

is it possible to use the [cliffparnitzky/checkedEmail](https://github.com/cliffparnitzky/CheckedEmail) field with [contao-bootstrap/form](https://github.com/contao-bootstrap/form)?

I could not find any kind of walkthrough on how to create custom form elements apart from this one: https://community.contao.org/de/showthread.php?52104-Template-Formular-Textfields

Currently, the field creates a table instead of the Bootstrap form groups due to ` <?php if (!$this->tableless): ?>` in form_checkedEmail.html5.

Deleting this block does not generate the wished outcome either.
```
 <?php echo $this->generateLabel(); ?> 
  <?php echo $this->generateWithError(); ?><br />
  <?php echo $this->generateConfirmationLabel(); ?> 
  <?php echo $this->generateConfirmation(); ?><br /> 
``` 

Any suggestions how I could edit the `generateLabel()` blocks to achieve Bootstrap widget styling?

Thank you!

**Comment by dmolineus** [comment]
As far as I see, the checked email widget uses two input fields.

To achieve the bootstrap stylings the [contao-form-helper](https://github.com/netzmacht/contao-form-helper/) is used which basically rebuilds every element (was required because before Contao 3.3 there was no template to edit form widgets).

To support the widget you have to:
 - Override the template and set up something like the form_password.html5 template: https://github.com/netzmacht/contao-form-helper/blob/master/module/templates/widget/form_password.html5
 - Implement an event listener which creates the repeat input field. Here's the reference of the password implementation
https://github.com/netzmacht/contao-form-helper/blob/master/src/Netzmacht/Contao/FormHelper/Subscriber/GenerateSubscriber.php#L73-L108

The alternative is to manually change the template without using the form helper.

Please use the [contao community](https://community.contao.org/de/) for further questions or contact me directly if you want to charge me with implementing it as part of contao-bootstrap.
