### ISSUE TITLE
Allow to use specific form config.

### ISSUE THREAD

**Issue by dmolineus** [contao-bootstrap/form#5]
At the moment each form using the default config. With the new backend configuration it should be possible now create multiple confiruations and pick one for a specific form.

**Comment by taleteller** [comment]
This is not only an issue with forms, but every form elements as well. For example the horizontal column ratio is hard coded as 3:9 for label and control. Giving you all form controls with the same width. 

However there is not much sense in having all widgets in uniform width. For exampla a zip codes or phone numbers field should be narrow fields. You might try to add a class like "col-sm-6" to the widgets class config, but it wont work since "form-control" overrides everything with 100%. 

The Bootstrap approach is to envelop the control with a <div> containing column classes. But thats the place where your hard coded "col-lg-9" config comes at play. This setting has to be changeable not only for the whole form, but every element. Preferable in a responsive way, like "col-xs-6 col-md-3", and without breaking the total of 12 columns including the label. Vertical forms dont control field width at all, producing a similar issue. 

This might not be too easy to resolve ...

**Comment by dmolineus** [comment]
> However there is not much sense in having all widgets in uniform width. For exampla a zip codes or phone numbers field should be narrow fields. You might try to add a class like col-sm-6 to the widgets class config, but it wont work since "form-control" overrides everything with 100%.

Well this is actually the way Bootstrap handles it. Maybe it would be an idea to use own `form-control-sm`   classes, give them the prefered width and add them in the backend.

The col classes are used to build the 2 columns. Using it to limit the widget size would lead to cols smaller than full width. I'm not sure if this would raise any issues.

What would be a great feature indeed would be supporting [column sizing](http://getbootstrap.com/css/#forms-control-sizes) (scroll down to the section) inside of the form. Using subcolumns in form is a way but then it continious using the horizontal layout.

**Comment by taleteller** [comment]
Custom classes is the approach I am currently using:
```.input-1  { width: 8.33333333% !important; }.input-2  { width: 16.66666667% !important; }
.input-3  { width: 25% !important; }
.input-4  { width: 33.33333333% !important; }
.input-5  { width: 41.66666667% !important; }
.input-6  { width: 50% !important; }
.input-7  { width: 58.33333333% !important; }
.input-8  { width: 66.66666667% !important; }
.input-9  { width: 75% !important; }
.input-10 { width: 83.33333333% !important; }
.input-11 { width: 91.66666667% !important; }
.input-12 { width: 100% !important; }```

But this only works unless you use adjacent elements like icons, because the class i specify in the backend allways applies to the control. Thus you get, for example, a half wide text field and an icon on the right border. 

Column sizing in Bootstrap, as mentioned, uses rows to keep the elements in line, its no matter when a row is below 12/12. This works for both adjustments.

**Comment by dmolineus** [comment]
I understand the issue. Did a short research. The Bootstrap devs recommend to use the col classes as long as they have no better solution. See https://github.com/twbs/bootstrap/issues/10311

It would lead to an extra div as I understand it (See http://jsfiddle.net/tdUtX/2/) for non horizontal form.

Not even sure what's the best way to implement it. I could add an extra input field for a class which is assigned to the `form-group` element. Which would be the easiest. And doing a check if it contains a `col-` class. If set it would not set the default horizontal class.

**Comment by taleteller** [comment]
Thats pretty much what i did when i came about the same with my datepicker widget. Introducing a new class field, to be applied to the input-group. 

Checking the existence of  a `col-*` class feels a bit like hidden magic. How about giving form elements a reference to a columnset? Might be a bit of overkill, but most flexible. Referencing a columnset could be a way to config the form columns as well.

**Comment by dmolineus** [comment]
Agree, the checking would be really magic. Maybe a checkbox to ignore the default `col-*` classes is the way to go.

I don't like the idea with the reference to the columnset. A columnset could have more columns, the form layout will have 2 (well, could be more if moving the errors to a third column, but that's not possible with the default templates). So it looks over-featured to me. It also adds the dependency between form and the grid-editor which I would like to avoid.

I think adding the class input for the container gonna solve it. It could be a place to insert the `input-*` classes here. So with extra css there is no need for any magic.
