### ISSUE TITLE
Custom form fields get handeled as 'text'

### ISSUE THREAD

**Issue by Taleteller** [contao-bootstrap/form#9]
I am using contao-bootstrap on a dev site and have to implement a form with date selection fields. Thus i imported 'contao-legacy/calendarfield' and selected such a field in a demo form. However, I dont get any kind of calendar field in the front end, but a plain 'text' input field. 

It seems like 'contao-bootstrap/form' is reverting all unkown widget types to 'text', limiting form functionality to a default set. 

However, I am not fixed to 'contao-legacy/calendarfield' since there is an bootstrap based datetime picker: http://www.malot.fr/bootstrap-datetimepicker/index.php available already as dev asset within contao.

I would love to implement a widget similar to 'bootstrap-select' found in this module, creating one myself. How do I register such a widget to get it working within this framework?

**Comment by dmolineus** [comment]
For the 'contao-legacy/calendarfield' issue, I opened an issue in the used form-helper library. Actually the goal is to fallback to the `Wwidget::generate()` method when an unknown form element is given. The issue here is that the calendar field extends from `FormTextField` and so the widget claims to be an text input.

There are several ways to integrate such a widget:
 - Create a custom widget (and use a custom `$widget->type`). The generate() Method should create a bootstrap prepared form control. 
 - Create a custom widget which pre generates an `Element` which can be handled by the form-helper. The advantage is that the bootstrap form classes can be added automatically.
 - Use a custom form field template. Then you have the full control and the form helper ignores it as it is triggered in the templates. 
 - The form helper is designed to be flexible for such requests. You can create an event subscriber which manipulates a text input which uses `date` validation and maybe have an additional checkbox to enable the date picker.

You can tell me which way you prefer and I can give you more hints.

**Comment by Taleteller** [comment]
Thanks, in the meantime i 'debugged' my way to the 'contao-form-helper' as well. I also found the subscriber events, but the example on the readme.md is way out of date, thus i had to dig thru the code for a while, to identify the correct call.

Since a widgets type is unreliable, its possibly smarter to identify them by their class. That way i managed to get a propper inputgroup button beside the input field. 

I will drop hasseling with 'contao-legacy/calendarfield', and implement a whole custom widget based on 'eternicode/bootstrap-datepicker'.

Thanks

**Comment by dmolineus** [comment]
I improved accessing the widget type by getting the one which is set in the form field configuration https://github.com/netzmacht/contao-form-helper/commit/f00380c276ccc015e3af3e7dd2fe745e6c270071. Works fine with the calendarfield.

Would be nice if you publish the link to the date widget if you're planning to make it available. :-)
